name: CI-CD .NET TicketMaster

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurer les dépendances
        working-directory: ./FilRouge_TicketMaster_MVC_Core
        run: dotnet restore

      - name: Compiler l'application
        working-directory: ./FilRouge_TicketMaster_MVC_Core
        run: dotnet build --no-restore -c Release

      - name: Exécuter les tests unitaires
        working-directory: ./FilRouge_TicketMaster_MVC_Core
        run: dotnet test --no-build -c Release --verbosity normal

      - name: Publier l'application
        working-directory: ./FilRouge_TicketMaster_MVC_Core
        run: dotnet publish -c Release -o ../publish

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construire et pousser l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: user/ticketmaster:latest

      - name: Scanner l'image Docker (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'user/ticketmaster:latest'
          format: 'table'
          exit-code: '1'