name: CI-CD .NET TicketMaster

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FilRouge_TicketMaster_MVC_Core

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurer, compiler, tester et publier l'application
        run: |
          dotnet restore
          dotnet build --no-restore -c Release
          dotnet test --no-build -c Release --verbosity normal
          dotnet publish -c Release -o ../publish

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construire et pousser l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: fabhass/ticketmaster:latest

      - name: Scanner l'image Docker (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'fabhass/ticketmaster:latest'
          format: 'table'
          exit-code: '0'